create database EXERCICIOS_PROCEDURES

CREATE TABLE DEPARTAMENTO (
	IDDEPARTAMENTO INT CONSTRAINT PK_DEPTO PRIMARY KEY IDENTITY(1,1),
	DEPTO VARCHAR(40) NOT NULL
)

CREATE TABLE FUNCIONARIO (
	IDFUNC INT CONSTRAINT PK_FUN PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(20),
	RG VARCHAR(50),
	EMAIL VARCHAR(50),
	DT_NASC DATETIME,
	SENHADESC VARCHAR(20),
	DEPARTAMENTO INT CONSTRAINT FK_DEPT FOREIGN KEY REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
)

CREATE TABLE SALARIO(
	IDSALARIO INT CONSTRAINT PK_SALARIO PRIMARY KEY IDENTITY(1,1),
	VALOR MONEY CONSTRAINT VALOR CHECK(VALOR > 0),
	OBS VARCHAR(1000),
	FUNCIONARIO INT CONSTRAINT FK_FUNCIONARIO FOREIGN KEY REFERENCES FUNCIONARIO(IDFUNC)
)

ALTER TABLE SALARIO
ADD DTPAGAMENTO DATETIME

INSERT INTO DEPARTAMENTO VALUES('LOGISTICA')

INSERT INTO FUNCIONARIO VALUES('AUGUSTO','111222333', '22354324','AUGUSTO@EMAIL.COM', '1988-07-19','SENHA', 1)

SELECT * FROM FUNCIONARIO 

INSERT INTO SALARIO 
VALUES(2050.49, 'SEM FALTAS NO PERÍODO', 4, '2014-01-25'),
(2534.00, 'INCLUI BONUS POR EQUIPE', 4, '2014-02-15'),
(1998.40, NULL, 4,'2014-03-18')

CREATE PROCEDURE SP_INSEREDEPARTAMENTO
@DEPTO VARCHAR(40)
AS
BEGIN
	INSERT INTO DEPARTAMENTO(DEPTO) VALUES(@DEPTO)
END

EXEC SP_INSEREDEPARTAMENTO 'EXPEDICAO'
EXEC SP_INSEREDEPARTAMENTO 'COMPRAS'
EXEC SP_INSEREDEPARTAMENTO 'FATURAMENTO'									  

ALTER TABLE FUNCIONARIO
ADD  DT_ADMISSAO DATETIME

SELECT * FROM FUNCIONARIO
CREATE PROCEDURE SP_INSEREFUNCIONARIO
	@NOME VARCHAR(60),
	@IDDEPT INT
			
AS
	BEGIN
		INSERT INTO FUNCIONARIO(NOME, DEPARTAMENTO)
		VALUES(@NOME, @IDDEPT)
	
	
	END


SELECT * FROM DEPARTAMENTO

EXEC SP_INSEREFUNCIONARIO 'GOMES', 1 
EXEC SP_INSEREFUNCIONARIO 'SOUSA', 3
EXEC SP_INSEREFUNCIONARIO 'FAGUNDES', 4

ALTER PROCEDURE SP_INSEREFUNCIONARIO
	@NOME VARCHAR(60),
	@CPF VARCHAR(20),
	@RG VARCHAR(50),
	@EMAIL VARCHAR(50),
	@DT_NASC DATETIME,
	@DT_ADMISSAO DATETIME,
	@SENHADESC VARCHAR(20),
	@IDDEPT INT
			
AS
	BEGIN
		INSERT INTO FUNCIONARIO(NOME, CPF, RG, EMAIL, DT_NASC, SENHADESC, DEPARTAMENTO, DT_ADMISSAO)
		VALUES(@NOME, @CPF, @RG, @EMAIL, @DT_NASC, @SENHADESC, @IDDEPT, @DT_ADMISSAO)

	END

	EXEC SP_INSEREFUNCIONARIO 'ADAO', '11.22.33.44', '1111111', 'ADAO@EMAIL.COM', '1999-04-15', '2013-07-10', 'AMOREVA', 1



CREATE PROCEDURE SP_INSERESALARIO
@VALOR MONEY,
@DATA DATETIME,
@OBS VARCHAR(1000),
@FUNCIONARIO INT

AS 

BEGIN
	INSERT INTO SALARIO(VALOR, OBS, FUNCIONARIO, DTPAGAMENTO)
	VALUES(@VALOR, @OBS, @FUNCIONARIO, @DATA)
END


SET DATEFORMAT DMY

EXEC SP_INSERESALARIO 1000, '05/05/2019', NULL, 5
EXEC SP_INSERESALARIO 1530, '15/05/2019', NULL, 4
EXEC SP_INSERESALARIO 1420, '01/06/2019', 'ATRASADO', 5
EXEC SP_INSERESALARIO 3090, '10/08/2019', NULL, 6
EXEC SP_INSERESALARIO 520, '02/07/2019', 'HOME OFFICE', 4
EXEC SP_INSERESALARIO 1502, '20/09/2019', NULL, 4

CREATE TABLE MEDIASALARIO(
 IDMEDIA INT CONSTRAINT PK_MEDIA PRIMARY KEY IDENTITY(1,1),
 FUNCIONARIO INT CONSTRAINT FK_MEDIA_FUNCIONARIO FOREIGN KEY REFERENCES FUNCIONARIO(IDFUNC),
 VLMEDIO MONEY
)


CREATE PROCEDURE SP_MEDIASALARIAL
@IDFUNC INT
AS 
	BEGIN
	
		INSERT INTO MEDIASALARIO(FUNCIONARIO, VLMEDIO)
		SELECT FUNCIONARIO, ROUND(AVG(VALOR),2)
		FROM SALARIO
		WHERE FUNCIONARIO = @IDFUNC
		GROUP BY FUNCIONARIO

	END


-- Exercícios de procedures

--1

exec SP_INSEREDEPARTAMENTO 'TI'

exec SP_INSEREDEPARTAMENTO 'LIMPEZA'

exec SP_INSEREDEPARTAMENTO 'ADMINISTRATIVO'

exec SP_INSEREDEPARTAMENTO 'MARKETING'

--2

SELECT * FROM FUNCIONARIO

EXEC SP_INSEREFUNCIONARIO 'JOAO', '00.52.74.44', '6345822', 'JOAO@EMAIL.COM', '2002-15-04', '2018-07-10', 'SENHALEGAL', 3
EXEC SP_INSERESALARIO 3124, '2020-20-10', 'TRABALHOU BEM', 9
EXEC SP_INSERESALARIO 3124, '2020-20-09', 'TRABALHOU BEM', 9
EXEC SP_INSERESALARIO 3124, '2020-20-08', 'FALTOU UM POUCO', 9
EXEC SP_INSERESALARIO 3124, '2020-20-07', 'TRABALHOU BEM', 9

EXEC SP_INSEREFUNCIONARIO 'JOSE', '11.83.52.62', '5824075358', 'JOSE@EMAIL.COM', '1999-04-12', '2018-07-10', 'SEMESSA', 1
EXEC SP_INSERESALARIO 2124, '2020-20-10', 'TRABALHOU BEM DEMAIS', 10
EXEC SP_INSERESALARIO 2124, '2020-20-09', 'TRABALHOU BEM DEMAIS', 10
EXEC SP_INSERESALARIO 2124, '2020-20-08', 'TRABALHOU BEM DEMAIS', 10
EXEC SP_INSERESALARIO 2124, '2020-20-07', 'TRABALHOU BEM DEMAIS', 10


EXEC SP_INSEREFUNCIONARIO 'ANA', '12.26.33.44', '85723852', 'ANA@EMAIL.COM', '1999-16-04', '2017-16-12', 'JOAOLINDO', 4
EXEC SP_INSERESALARIO 2124, '2020-20-10', 'TRABALHOU BEM DEMAIS', 11
EXEC SP_INSERESALARIO 2124, '2020-20-09', 'TRABALHOU BEM DEMAIS', 11
EXEC SP_INSERESALARIO 2124, '2020-20-08', 'TRABALHOU BEM DEMAIS', 11
EXEC SP_INSERESALARIO 2124, '2020-20-07', 'TRABALHOU BEM DEMAIS', 11



EXEC SP_INSEREFUNCIONARIO 'FERNANDA', '83.78.23.49', '895435903', 'FER@EMAIL.COM', '1999-04-11', '2013-07-10', 'AMORETERNO', 4



--3
--a
SELECT *FROM SALARIO 
	INNER JOIN FUNCIONARIO 
	ON FUNCIONARIO.IDFUNC = SALARIO.FUNCIONARIO
CREATE PROCEDURE SP_EXCLUIRREGISTRO
@NOME VARCHAR(40),
@DATA DATETIME 
AS

BEGIN
	DELETE FROM SALARIO WHERE DTPAGAMENTO = @DATA
	AND
	@NOME =
	(SELECT FUNCIONARIO.NOME FROM FUNCIONARIO 
	INNER JOIN SALARIO 
	ON FUNCIONARIO.IDFUNC = SALARIO.FUNCIONARIO
	)

	SELECT * FROM SALARIO
END


--b
create procedure sp_alterarfuncionario
	@ID int,
	@NOME VARCHAR(60),
	@CPF VARCHAR(20),
	@RG VARCHAR(50),
	@EMAIL VARCHAR(50),
	@DT_NASC DATETIME,
	@DT_ADMISSAO DATETIME,
	@SENHADESC VARCHAR(20),
	@IDDEPT INT

	as
	begin
		update funcionario
		set NOME = @NOME,
		CPF = @CPF,
		RG = @RG,
		EMAIL = @EMAIL,
		DT_NASC = @DT_NASC,
		DT_ADMISSAO = @DT_ADMISSAO,
		SENHADESC = @SENHADESC,
		DEPARTAMENTO = @IDDEPT
		WHERE IDFUNC = @ID
	
	end


	select * from funcionario
	EXEC sp_alterarfuncionario 4, 'Augusto', '1111112334','46346534566','agusto@email.com','1999-04-11', '2019-04-06','amorZinho', 1 

--c
create procedure sp_excluirfuncionario
@nome varchar(40)

as
	begin		

		delete FROM FUNCIONARIO
		where NOME = @nome

	end

ALTER PROCEDURE sp_excluirfuncionario
@nome varchar(40)
as
	begin		
		exec SP_EXCLUIRREGISTRO '2019-05-11', @nome

		delete FROM FUNCIONARIO
		where NOME = @nome

	end

exec sp_excluirfuncionario 'GOMES'